title: Sam Hoffman
description: >-
  Hi! I'm a data wrangler, climber, dreamer, and learner of languages.  
baseurl: /
url: https://sam-hoffman.me
include: ['_pages']

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge